- name: Check if EC2 instance exist or not
  hosts: localhost
  connection: local

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_pair_name }}"
        vpc_subnet_id: "{{ vpc_subnet_id}}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_group }}"
        network:
          assign_public_ip: "{{ network.assign_public_ip }}"
        image_id: "{{ image_id }}"
        tags:
          Environment: Testing
        volumes:
          - device_name: /dev/xvda
            ebs:
              delete_on_termination: true
